### ISSUE TITLE
issue: Invoke Agent via API call

### ISSUE THREAD

**Issue by machinefriendly** [architecturebytes/vertex-ai-agents#1]
By following your guidance I created service account with mentioned role, and generate the token with your code, however, by calling API with that token, it returns:
_{"error":{"code":403,"message":"Caller does not have required permission to use project sig-knowledge-base. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=sig-knowledge-base and then retry. Propagation of the new permission may take a few minutes.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Google developer console IAM admin","url":"https://console.developers.google.com/iam-admin/iam/project?project=sig-knowledge-base"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"USER_PROJECT_DENIED","domain":"googleapis.com","metadata":{"consumer":"projects/sig-knowledge-base","service":"dialogflow.googleapis.com"}}]}}_
then I added that Service Usage Consumer role and call again, I got the new 400 error:
_{"error":{"code":400,"message":"Please refer to https://cloud.google.com/dialogflow/cx/docs/concept/region#avail and https://cloud.google.com/dialogflow/es/docs/how/region#regions to find the correct endpoint to access resources located in 'REGION_ID'.","status":"INVALID_ARGUMENT"}}_
I use eu as REGION_ID which is one shown in the agent list column location, and cannot see what issue is, could you help? Thanks in advance.

**Comment by machinefriendly** [comment]
I find the cause of the issue, according to the doc https://cloud.google.com/dialogflow/vertex/docs/quick/api
the API URL should have subdomain_region at beginning, for my case it is https://eu-dislogflow.googleapi.com...
Withi this update, it works now, thanks.

**Comment by architecturebytes** [comment]
Glad the issue is resolved!
As you may know - access token expires after a while, so provision to renew it as needed.

**Comment by machinefriendly** [comment]
@architecturebytes thanks for reminding. In order to get the valid token, I host your getAccessToken.py in a Google Cloud function with unauthenticated calling, and every time I call Vertex agent via API I call that cloud function firstly. Given I call agent via API from a specific environment in which Google Auth package is not available, this is the solution I can find so far.

**Comment by architecturebytes** [comment]
Depending on your environment - you can make some improvements to security.
One thing though - you don't need to generate new Access Token before 'every' Agent Call - keep reusing the Access Token until it expires (default I guess is 1 hour). The access credentials has expiry property you can refer to. GetAccessToken.py is updated to include that information.

**Comment by machinefriendly** [comment]
@architecturebytes thanks. Regarding the function security, a key is required as request parameter. Thanks for the proposition of expiration verification, however, due to the stateless of cloud function, I cannot see an easy way to store the token and its expiry info for a verification during a next running.

**Comment by architecturebytes** [comment]
You would store(cache) it on client side (caller).
